hashthat/hashthat/urls.py
from django.contrib import admin
from django.urls import path
from hashing import views as hashing_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', hashing_views.home, name="home"),
    path('hash/<str:hash>', hashing_views.hash, name="hash"),
    path('quickhash', hashing_views.quickhash, name="quickhash"),
]

hashthat/hashing/models.py
from django.db import models

# Create your models here.

class Hash(models.Model):
    text = models.TextField()
    hash = models.CharField(max_length=64) # limit only for sha256 so far
    algo = models.CharField(max_length=32, default='sha256') # hash method from pulldown

hashthat/hashing/forms.py
from django import forms
import hashlib


class HashForm(forms.Form):
    choices = [(e, e) for e in hashlib.algorithms_available]
    algo = forms.ChoiceField(choices=choices, widget=forms.Select)
    text = forms.CharField(label='Enter text here:', widget=forms.Textarea)

hashthat/hashing/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse

from .forms import HashForm
from .models import Hash

from .utils import get_hash


def home(request):
    form = HashForm(initial={'algo': 'sha256'})
    text_hash = ''
    if request.method == 'POST':
        filledForm = HashForm(request.POST)
        if filledForm.is_valid():
            text = filledForm.cleaned_data['text']
            algo = filledForm.cleaned_data['algo']
            
            text_hash = get_hash(algo, text)

            try:
                Hash.objects.get(hash=text_hash, algo=algo)
            except Hash.DoesNotExist:
                hash = Hash()
                hash.algo = algo
                hash.hash = text_hash
                hash.text = text
                hash.save()

            return redirect('hash', hash=text_hash)
        
    return render(request, 'hashing/home.html', {'form': form, 'hash': text_hash})

def hash(request, hash):
    hash = Hash.objects.get(hash=hash)
    return render(request, 'hashing/hash.html', {'hash': hash})

def quickhash(request):
    text = request.GET['text']
    data = {'hash': get_hash('sha256', text)}
    return JsonResponse(data)

hashthat/hashing/templates/hashing/base_template.html
<!doctype html>
<html lang="en">
  <head>
    <title>Hashtool</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block content %}

    {% endblock content%}
  </body>
</html>

hashthat/hashing/templates/hashing/hash.html
{% extends 'hashing/base_template.html' %}
{% block content %}

  <p>hash text: {{ hash.text }}</p>
  <p>hash: {{ hash.hash }}</p>
  <p>hash algo: {{ hash.algo }}</p>

<a href="{% url 'home' %}">Back</a>
{% endblock content %}

hashthat/hashing/templates/hashing/home.html
{% extends 'hashing/base_template.html' %}
{% block content %}

  <form action="{% url 'home' %}" method="post">
      {% csrf_token %}
      {{ form.as_p }}
    <button type="submit" class="btn btn-primary" name="submit">Submit</button>
  </form>
      
  <h2 id="quickhash"></h2>
  
  <script>
  $('#id_text').keyup(function() {
   let text = $(this).val();
   $.ajax({
     url: '/quickhash',
     data: {
       text: text,
     },
     dataType: 'json',
     success: function(data) {
       $('#quickhash').text(data['hash']);
     }
   });
  });
  </script>
  {{ hash }}

{% endblock content %}